### ISSUE TITLE
Ascii ERROR

### ISSUE THREAD

**Issue by an0Nym0us63** [tielvh/emby-ntfy-notifications#1]
it seems the plugin doesnt handle UTF8 characters

Most of my notifications results in an error HEADER MUST CONTAIN ONLY ASCII CHARACTERS

The test notification works

**Comment by tielvh** [comment]
Good catch ;) All my notifications have been with ASCII characters.

I've updated the plugin to be able to handle UTF-8 characters, check out this new release: [https://github.com/tielvh/emby-ntfy-notifications/releases/tag/1.0.0.1](https://github.com/tielvh/emby-ntfy-notifications/releases/tag/1.0.0.1).
I tested it with 4.7.14.0, I'm still updating things to be compatible with 4.8.1.0...

Let me know if that fixes your problem

**Comment by an0Nym0us63** [comment]
Hello

I missed your reply, yes it works as expected now

Thanks for the update
